-- Supabase 数据库表结构
-- 在 Supabase 的 SQL Editor 中执行此脚本

-- 1. 创建业主凭证表
CREATE TABLE IF NOT EXISTS owner_credentials (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    owner_id TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. 创建商品表
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id TEXT NOT NULL,
    name TEXT NOT NULL,
    link TEXT,
    checked BOOLEAN DEFAULT false,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    brand TEXT,
    size JSONB DEFAULT '{"length":"","width":"","height":""}'::jsonb,
    image TEXT,
    notes TEXT
);

-- 3. 创建管理员日志表
CREATE TABLE IF NOT EXISTS admin_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    action TEXT NOT NULL
);

-- 4. 创建索引
CREATE INDEX IF NOT EXISTS idx_products_owner_id ON products(owner_id);
CREATE INDEX IF NOT EXISTS idx_products_updated_at ON products(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_logs_timestamp ON admin_logs(timestamp DESC);

-- 5. 启用行级安全性 (RLS)
ALTER TABLE owner_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_logs ENABLE ROW LEVEL SECURITY;

-- 6. 创建 RLS 策略 - 允许所有操作（开发环境）
-- 注意：生产环境建议更严格的策略

-- owner_credentials 策略
CREATE POLICY "Enable all operations for owner_credentials"
    ON owner_credentials
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- products 策略
CREATE POLICY "Enable all operations for products"
    ON products
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- admin_logs 策略
CREATE POLICY "Enable all operations for admin_logs"
    ON admin_logs
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- 7. 创建更新时间触发器函数
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 8. 为表添加更新时间触发器
CREATE TRIGGER update_owner_credentials_updated_at
    BEFORE UPDATE ON owner_credentials
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_products_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
